# GitHub Pages Configuration for Cielonline QR Studio
# This configuration enables GitHub Pages for this repository

# Site settings
title: Cielonline QR Studio
description: QR codes made for you!
url: https://cielonline.com

# Build settings
markdown: kramdown
exclude:
  - README.md
  - .git
  - .gitignore

